Traceback (most recent call last):
  File "/home/group4/Desktop/dht_test/myenv/finalmaincode.py", line 225, in <module>
    asyncio.run(main()) #error
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
  File "/home/group4/Desktop/dht_test/myenv/finalmaincode.py", line 212, in main
    await task3
  File "/home/group4/Desktop/dht_test/myenv/finalmaincode.py", line 194, in Heating2
    for i in range(steps_to_takeH):
TypeError: 'float' object cannot be interpreted as an integer
invalid command name "548622970176update_temp_display"
    while executing
"548622970176update_temp_display"
    ("after" script)
invalid command name "548622974208update_temp_display"
    while executing
"548622974208update_temp_display"
    ("after" script)

async def update_sensors():
    global temperature_f1, humidity1, temperature_f2, humidity2
    while True:
        try:
            temperature_f1 = sensor1.temperature * (9 / 5) + 32
            humidity1 = sensor1.humidity
            temperature_f2 = sensor2.temperature * (9 / 5) + 32
            humidity2 = sensor2.humidity
        except RuntimeError as error:
            print(f"Sensor error: {error.args[0]}")
        await asyncio.sleep(3.0)

